# azldev is a statically-linked Go binary; there is no useful -debuginfo to
# extract, so disable the debug package to keep the build simple.
%global debug_package %{nil}

Name:           azldev
Version:        0.2.0
Release:        1%{?dist}
Summary:        Developer tooling for the Azure Linux distribution

License:        MIT
URL:            https://github.com/microsoft/azure-linux-dev-tools
# Generated by tito from git; contains the full source tree including the
# committed `vendor/` directory so the build can run fully offline in mock.
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  golang >= 1.25
BuildRequires:  git-core

%description
azldev (Azure Linux developer tools) parses, resolves, and queries the
TOML-based metadata that defines Azure Linux, prepares component sources for
building with mock, fetches source archives from lookaside caches, and offers
convenience utilities for locally building individual packages and images.

%prep
%autosetup -n %{name}-%{version}

%build
# Keep all Go caches inside the (writable) build dir; mock buildroots have no
# writable $HOME and no network access.
export GOPATH="%{_builddir}/gopath"
export GOCACHE="%{_builddir}/gocache"
export GOFLAGS="-mod=vendor -trimpath"
export CGO_ENABLED=0

# Derive a reproducible build date from SOURCE_DATE_EPOCH when tito/rpmbuild
# provides it, otherwise fall back to "now".
builddate="$(date -u -d "@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y-%m-%dT%H:%M:%SZ)"

# -buildmode=pie: hardened, position-independent executable (Fedora default).
# -ldflags "-s -w": strip symbol table and DWARF; we ship no -debuginfo package.
go build \
    -buildvcs=false \
    -buildmode=pie \
    -ldflags "-s -w -X go.szostok.io/version.version=%{version} -X go.szostok.io/version.buildDate=${builddate}" \
    -o azldev \
    ./cmd/azldev

%install
install -D -m 0755 azldev %{buildroot}%{_bindir}/azldev

# Shell completions (Cobra generates these at runtime).
install -d %{buildroot}%{_datadir}/bash-completion/completions
%{buildroot}%{_bindir}/azldev completion bash > \
    %{buildroot}%{_datadir}/bash-completion/completions/azldev

install -d %{buildroot}%{_datadir}/zsh/site-functions
%{buildroot}%{_bindir}/azldev completion zsh > \
    %{buildroot}%{_datadir}/zsh/site-functions/_azldev

install -d %{buildroot}%{_datadir}/fish/vendor_completions.d
%{buildroot}%{_bindir}/azldev completion fish > \
    %{buildroot}%{_datadir}/fish/vendor_completions.d/azldev.fish

%files
%license LICENSE
%doc README.md
%{_bindir}/azldev
%{_datadir}/bash-completion/completions/azldev
%{_datadir}/zsh/site-functions/_azldev
%{_datadir}/fish/vendor_completions.d/azldev.fish

%changelog
* Mon Jul 27 2026 Azure Linux Dev Tools <azldev@microsoft.com> - 0.2.0-1
- Initial RPM packaging of azldev.
